name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -r requirements.txt

      - name: Determine version
        id: get-version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # Use tag version (e.g. v1.2.3)
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            # Create a dev version like 1.2.3.dev20250722153000
            BASE_VERSION=$(grep -oP "(?<=^version = \")\d+\.\d+\.\d+" pyproject.toml)
            VERSION="${BASE_VERSION}.dev$(date -u +%Y%m%d%H%M%S)"
          fi

          echo "Using version: $VERSION"
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set version in pyproject.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ env.PACKAGE_VERSION }}\"/" pyproject.toml

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
